server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://47.97.200.47:3306/ming_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: sunming
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
    # redis配置
  redis:
    host: 47.97.200.47
    port: 6379
    password: sunming
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKeySecret: P23xOdzFWuQhqdIb3cVDu0ah2xVPKV
  accessKeyId: LTAI5tR47yXPpMoPpwoDN8LD
  endpoint: oss-cn-hangzhou.aliyuncs.com
  bucketName: mingblog2020